config.go
go.mod
go.sum

The xtgo/uuid library is 11 years old, and has been superseded by google/uuid
Simple change to just switch over to the new uuid library, increasing supportability.

Replace xtgo/uuid with Google's uuid library

---

featureflags.go

fixes a nil panic when unable to fetch feature flags and `err != nil` which means `res.Body` will be nil at defer time because we aren't returning early enough from the method

fix: fixes a nil panic when unable to fetch feature flags

---

feature_flags_test.go
featureflags.go

When the operator type is unknown, raise inconclusive match error, so we don't incorrectly match on unknown operator types, which is pretty important for when we extend flags to support more operators.

fix(flags): Don't match unknown operators

---

config.go

Docs specify that default interval is 5 minutes while in practice it is 5 seconds.

Fix default feature flags polling interval

---

posthog.go
posthog_test.go

When capturing an event with SendFeatureFlags set to true and no properties defined posthog panics with nil pointer.
Panic:
```
github.com/posthog/posthog-go.(*client).Enqueue(0x4000abba00, {0x420b130?, 0x40015705a0?) 
/root/go/pkg/mod/github.com/posthog/posthog-go@v0.0.0-20240110105835-f2ee529330e9/posthog.go:194
```
Example:
```go
client.Enqueue(posthog.Capture{
DistinctId: user.ID,
Event:      "test_event",
SendFeatureFlags: true,
})
```

Initialize properties map when sending feature flags

---

featureflags.go

Atm it is impossible to tell which flag failed to be computed locally.
Before:
```
Unable to compute flag locally - Can't determine if feature flag is enabled or not with given properties
```
After:
```
Unable to compute flag locally (my_test) - Can't determine if feature flag is enabled or not with given properties
```

Log flag name when failed to compute it locally

---

.github/workflows/unit-tests.yml
feature_flags_test.go
featureflags.go
fixtures/feature_flag/test-complex-cohorts-locally.json
fixtures/feature_flag/test-complex-cohorts-negation-locally.json
go.mod
go.sum

> 3. There's more than one cohort in the feature flag definition.
This restriction is annoying. Copying what [NodeJS SDK does](https://github.com/PostHog/posthog-js-lite/pull/85).
Ref: https://posthog.com/docs/feature-flags/local-evaluation
PS Sorry I couldn't reopen my old PR somehow :/

Support multiple cohorts in local evaluation

---

config.go
featureflags.go
posthog.go

TLDR: We want to poll at the same time from all instances.
Atm the feature flags poller will be executed every 5 minutes by default. When running posthog poller from multiple instances we have no guarantees when flags will be fetched. In the example below we will have different state on two instances between 12:10-12:12.
This PR allows specifying a function that would calculate when flags should be fetched next.
```mermaid
sequenceDiagram
participant A as Instance A
participant P as Posthog
participant B as Instance B
Note over A: Start new instance at 12:00
Note over B: Start new instance at 12:02
A->>P: Poll flags at 12:05
B->>P: Poll flags at 12:07
A->>P: Poll flags at 12:10
P->>P: Disable the flag in the dashboard
B->>P: Poll flags at 12:12
```

Allow to configure when next flags polling happens

---

feature_flags_test.go
featureflags.go
posthog.go

If we get HTTP timeouts or server errors then this SDK will happily block itself.
In case of an error `poller.loaded <- false` will block indefinitely since we read from this channel only once. Blocking on the channel will in turn block the infinite loop that polls for the latest state. SDK users are not blocked but will get outdated flags' state.
Tests before:
```
> go test -run TestFetchFlagsFails -timeout 5s
panic: test timed out after 5s
running tests:
TestFetchFlagsFails (5s)
...
goroutine 35 [chan send]:
github.com/posthog/posthog-go.(*FeatureFlagsPoller).ForceReload(...)
/Users/roman/Code/trial/posthog-go/featureflags.go:874
github.com/posthog/posthog-go.(*client).ReloadFeatureFlags(0x140001a40d8?)
/Users/roman/Code/trial/posthog-go/posthog.go:272 +0x34 …
```

Do not push to the loaded channel when flags' request fails

---

CHANGELOG.md
version.go

Golang requires a `v2` folder for major versions like `2.0.0`. We don't really want to do that yet since we are not any major versions ahead of 1.0 yet and have never really used SEMVER.
Let's just reset this to `v1.2.1`

fix: change version from 2.0 to 1.2 (we are not on v2 yet)

---

featureflags.go

We get error responses from the API with no details about why (e.g. rate limiting) and we'd like to see that HTTP response payload appear in the error log rather than what's currently displayed:
```
ERROR: Unable to fetch feature flags%!(EXTRA <nil>)
```
Also, there were several invocations of `poller.Errorf` that were missing the Go format string verb (`%s`).

Better error for feature flags fetch without errors. Adds missing format string verbs to poller Errorf.

---

.github/workflows/bump-version.yml

We need to make sure that every land to master bumps the version so people can pin a version with confidence. This allows that.

feat: allow labels to bump patch/minor versions

---

.github/workflows/bump-version.yml

- Use the default GITHUB_TOKEN for gh cli
- Use a new Personal Access Token for getting around branch rules requiring a PR

fix: Use the default github action token for pushing

---

config.go
fixtures/test-merge-capture.json
posthog.go
posthog_test.go
properties.go
properties_test.go

This is going to be useful for me because I have several Go services, and I want to differentiate between them in the dashboard insights.
```
posthogClient, err = posthog.NewWithConfig(
"phc_",
posthog.Config{
BatchSize:  1,
Endpoint:  "https://us.i.posthog.com",
...
DefaultEventProperties: posthog.NewProperties().Set("service", "api"),
},
)
```

Add ability to define event properties across all events

---

properties.go
properties_test.go

Properties.Merge: check for nil

---

config.go

Addresses this issue: https://github.com/PostHog/posthog-go/issues/74

fix config docs

---

README.md

The community Slack has been deprecated. This PR points users to (what I think is) the next best option

Chore: Correct the questions link

---

README.md
examples/README.md
examples/capture.go
examples/featureflags.go
examples/main.go

And improve how we run the examples. They now can read project (and personal) api keys from env vars. If not present, they'll prompt for them.

Add some development instructions

---

feature_flags_test.go
featureflags.go
posthog.go
posthog_test.go

The words "true" and "false" are valid variant keys. It's incorrect to convert them to `true` and `false`. This could result in a case where `isEnabled` returns `false` when in fact, it's `true` but the variant selected is named "false".
This PR fixes the bug by not converting flag values from `string` to `bool`. There's also a new test to confirm this change.
The PR also makes the examples read from env vars for the project api key, personal api key, and endpoint. Makes it easier to switch between local dev and prod.
I documented these changes in the respective READMEs.

fix: Do not convert string variant results into bool

---

decide.go
featureflags.go
posthog.go

There were two implementations of decide. That's not the end of the world, but I'm about to implement a new decide format (`/decide?v=4`) and I don't want to have to do it in two places.
So this adds a new file `decide.go` with a new interface `decider` and an implementation `decideClient` that both `Client` and `FeatureFlagsPoller` uses.

refactor: Consolidate decide code

---

executor.go

Just a small refactor to make the Go task execution faster/cheaper without changing the core behavior.

Simplify executor implementation

---

alias.go
capture.go
config.go
config_test.go
featureflags.go
fixtures/test-enqueue-alias.json
fixtures/test-enqueue-capture-with-disable-geoip.json
fixtures/test-enqueue-capture-with-uuid.json
fixtures/test-enqueue-group-identify.json
fixtures/test-enqueue-identify.json
fixtures/test-interval-capture.json
fixtures/test-many-capture.json
fixtures/test-merge-capture.json
fixtures/test-timestamp-capture.json
flags.go
group_identify.go
identify.go
posthog.go
posthog_test.go

Bring the **DisableGeoIP** option to Go SDK.
This PR is backward incompatible, but posthog-python and doc compatible.
Since now the Go sets `$geoip_disable` by default on all capture events and `geoip_disable` on feature flag requests.
With few tweeks, this is based on https://github.com/PostHog/posthog-go/pull/83/files #83  and @jackhopner contribution.
#31 has been assimilated

feat: add DisableGeoIP option

---

capture.go
examples/capture.go
feature_flags_local_test.go
featureflags.go
posthog.go
posthog_test.go
version.go

The current `SendFeatureFlags` boolean parameter provides limited control over feature flag evaluation behavior. Users couldn't specify evaluation preferences or custom properties per capture event.
Modified `SendFeatureFlags` to accept either:
- `bool` (existing behavior, fully backward compatible)
- `*SendFeatureFlagsOptions` struct with granular control:
```go
type SendFeatureFlagsOptions struct {
OnlyEvaluateLocally bool              // Force local vs remote evaluation
PersonProperties    Properties        // Custom properties for this event
GroupProperties     map[string]Properties  // Custom group properties
}
```
- Declarative control: Explicitly specify local vs remote evaluation per event
- Custom properties: Supply event-specific properties without affecting global state
- …

feat(flags): make the `SendFeatureFlags` parameter more declarative and ergonomic
